### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by leeson1995** [nats-io/nkeys#17]
![image](https://user-images.githubusercontent.com/48010956/61273978-56f4b700-a7dd-11e9-8634-de74b8627886.png)
pls help~

**Comment by c0mradeuc** [comment]
Please help i have a similitar problem

**Comment by derekcollison** [comment]
Is this still an issue or can this be closed?

**Comment by derekcollison** [comment]
Closing for now, feel free to re-open if needed.
