### ISSUE TITLE
usage intent

### ISSUE THREAD

**Issue by ghost** [nats-io/nkeys#6]
I want to use call into NATS over the WAN, and so was wondering if this package makes sense for that.
As far as i can see i need to create a public key to give to the Golang NATS Client to use, and on the NATS server is will use it to recognise the specific user ?

Is there any over the wire encryption though, since i am talking over the WAN ?

EDIT:
Also is this integratde into NATS Servers and Clients yet as i dont see it is ?

**Comment by derekcollison** [comment]
This is handled for you in NATS 2.0. We do not encrypt, however the client never shares its private key with the NATS system.

https://nats-io.github.io/docs/nats_server/jwt_auth.html#the-authentication-process
