### ISSUE TITLE
Exit status '1' when showing nk version

### ISSUE THREAD

**Issue by sboulkour** [nats-io/nkeys#61]
### What version were you using?

nk version v0.4.6_62e5d8c7c4af84283b6535bcbf1300ab25b45e2d

### What environment was the server running in?

Ubuntu amd64 23.10

### Is this defect reproducible?

I can repruce each time : when typing "nk -v" to display version, exit status is 1.
Also, it displays all usage info where limiting to version info is sufficiant. Displaying usage info is redundant from my pov.

### Given the capability you are leveraging, describe your expectation?

I expect the cli to display only its version, and to gracefully exit with status 0. 

### Given the expectation, what is the defect you are observing?

On a side note, all other NATS cli (nats, nats-top, nsc) do use "--version" parameter to show version, where nk use "-v" alone. As a new NATS user, the experience doesnt feel consistent between nats-io repos (remark also works with docker images for example, as they aren't builds around same principles between repos)

**Comment by sboulkour** [comment]
My use case : I build a conainer image with some tools, and as test step, i execute each installed tool to display its version. Current behavior breaks the CI pipeline :)

**Comment by derekcollison** [comment]
I will get it fixed, thanks for the report.

**Comment by derekcollison** [comment]
Should be fixed, will do release next week.

**Comment by derekcollison** [comment]
I actually did the release now, 0.4.7. You should be good to go.
