### ISSUE TITLE
Version missing

### ISSUE THREAD

**Issue by lennard-pfennig-bruker** [nats-io/nkeys#63]
### What version were you using?

v0.4.7

### What environment was the server running in?

- Apple M1 Pro arm64
- ubuntu 20.04 amd64

### Is this defect reproducible?
yes, every time so far.

```bash
> go install github.com/nats-io/nkeys/nk@latest
> nk -v
nk version

> go install github.com/nats-io/nkeys/nk@v0.4.7
> nk -v
nk version
```

### Given the capability you are leveraging, describe your expectation?

```bash
> go install github.com/nats-io/nkeys/nk@latest
> nk -v
nk version v0.4.7

> go install github.com/nats-io/nkeys/nk@v0.4.7
> nk -v
nk version v0.4.7
```

### Given the expectation, what is the defect you are observing?

I assume the version did not get set during the build process, as the comment in `main.go` suggest

```go
// this will be set during compilation when a release is made on tools
var Version string
```

**Comment by lennard-pfennig-bruker** [comment]
I do not have the fix, because I do not usually work with your toolchain. But maybe some suggestions for the readme page https://github.com/nats-io/nkeys/pull/64

**Comment by lennard-pfennig-bruker** [comment]
Was just looking at https://goreleaser.com/cookbooks/using-main.version/, is it possible that all that needs to be done is rename `Version` to `version` in [main.go](https://github.com/nats-io/nkeys/blob/c865baf4058b0ae6529eeb82fbe86bd8c21f4a36/nk/main.go#L32)?

**Comment by derekcollison** [comment]
I thought I fixed that, will take another look.

**Comment by derekcollison** [comment]
Just use goreleaser to build it and it works properly.

**Comment by derekcollison** [comment]
Or install from a release..

**Comment by lennard-pfennig-bruker** [comment]
is `go install github.com/nats-io/nkeys/nk@v0.4.7` not installing from a release?
