### ISSUE TITLE
rolling one's own crypto 

### ISSUE THREAD

**Issue by glycerine** [nats-io/nkeys#8]
> The NATS system will utilize Ed25519 keys, meaning that NATS systems will never store or even have access to any private keys. Authentication will utilize a random challenge response mechanism.

Please hire a cryptographic consultant to help design this, rather than roll your own crypto as this implies.

**Comment by pentateu** [comment]
"cryptographic consultant" ? hunn.. they are great ! As you can see all the good software in GitHub is done by "Experts". "cryptographic consultants", "web consultants", "mobile consultants" and etc.
;)

**Comment by pentateu** [comment]
Joke aside.. as far as I could understand so far..  this project uses the ed25519 implementation -->  https://godoc.org/golang.org/x/crypto/ed25519"
and is not trying to do its own crypto implementation.

**Comment by derekcollison** [comment]
That is correct. We do have an encoding that simply makes them printable, selectable on double click and have a prefix that determines type so they can be visually distinguished. The signing is Ed25519 and supplied by Google's crypto team.
